// GENERATED by scripts/process-assets.mjs - do not edit by hand.
// Every entry carries intrinsic width/height so <Picture> can reserve the
// box before load and hold CLS at zero.

export const images = {
  "hero-bed": {
    "slug": "hero-bed",
    "width": 1696,
    "height": 2528,
    "aspect": 0.6709,
    "widths": [
      640,
      1024,
      1600
    ],
    "fallback": 900,
    "lqip": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAADwBACdASoYACQAPuVeqU2pJSQiMAqpIByJQBZZgEc1L+eioGmAu4SgeKxdJ4glCgAA+aOVnIYc2j3MyW5v7lAavrshypEGx2y6qto6TwjKJ1mDVYU62/SKuy1fjHrr078AOdtrFqalqY5AtsumuUuFFsDFidfFUpkFefYf9nGmEGRhzaP3fJMV+d3LFw6AAAA=",
    "role": "Hero still + mobile fallback. Same room as the hero video."
  },
  "showroom-wide": {
    "slug": "showroom-wide",
    "width": 3168,
    "height": 1344,
    "aspect": 2.3571,
    "widths": [
      640,
      1024,
      1600
    ],
    "fallback": 900,
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAwCdASoYAAoAPu1kqk4ppaQiMAgBMB2JQBOgAsNRH7ZW/2z8AAD+mC0cXe6SmKKUJ4ikvINoaL5b+N0XsrrAx3rGg8rSiCF48ArC2VZMBAAA",
    "role": "Intro full-bleed band. Widest frame in the set (3168x1344)."
  },
  "living": {
    "slug": "living",
    "width": 1024,
    "height": 1024,
    "aspect": 1,
    "widths": [
      640,
      1024
    ],
    "fallback": 900,
    "lqip": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADwBACdASoYABgAPu1ur1IppiQiqAgBMB2JZACdMxyBSA6XNjXr8LJYsuBwBB+QOQAA/h3CjTDqyy4bxKXFmqlypvU4Lx5HBT/Xg1O1PCXRftbB7WrrpeuvU502gVfR3El23snfrysYB0No0tKJ8OpINf9Nw6I2rvNTQAAA",
    "role": "Collections - Living. Gilt frame, grey velvet, embroidery."
  },
  "bedroom": {
    "slug": "bedroom",
    "width": 1122,
    "height": 1402,
    "aspect": 0.8003,
    "widths": [
      640,
      1024
    ],
    "fallback": 900,
    "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAACwBQCdASoYAB4APu1cqk4ppKOiMBgMATAdiUATpfregAAv8X/ofp25omPUpJU2Dnkpgqo7ZRQA/H35ZP/dLtmplo86bro6AN/arnxWY3Koftlw8dWLJiGrCRjdxjldLk9Gll/DSJvNSEL7BP/AoXE2d7dvwYGuWVbExEuQ3saLn8ddQ14ScRRTcqCqAAAA",
    "role": "Collections - Bedroom. The only image carrying the brand teal."
  },
  "dining": {
    "slug": "dining",
    "width": 1087,
    "height": 1447,
    "aspect": 0.7512,
    "widths": [
      640,
      1024
    ],
    "fallback": 900,
    "lqip": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAABQBQCdASoYACAAPu1qr1CppaQiqAqpMB2JQBdmcBAXlSmXbaCEnmFwFS++jVZyZcZGY8AA6xezA0HQuHWM2YcewsZu92F82QYKxlV8ILY14Egwifi+OTTqMnoUz5pz+klsCnvZbztaX5cbkk2Bs2X+pb/VU3HG+zqT4k1vphMUxs52+ANoO0AAAAA=",
    "role": "Collections - Dining. Most credible photograph in the set."
  },
  "bespoke": {
    "slug": "bespoke",
    "width": 2048,
    "height": 2048,
    "aspect": 1,
    "widths": [
      640,
      1024,
      1600
    ],
    "fallback": 900,
    "lqip": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAwBQCdASoYABgAPu1iqE2ppaOiMBgMATAdiWUArAANuW0tY94QKCpZbAX8XaCBAc2EAAD5xw9DkJxTrBb4kSe86md5PgaCj2DF7xtTFs+WyGM/6W172Y9cVVSgv+ZnvdsDi6/TL8s1yJMcjpEAAA==",
    "role": "Collections - Bespoke. Carved chairs on a seamless backdrop."
  },
  "showroom-hall": {
    "slug": "showroom-hall",
    "width": 1344,
    "height": 1776,
    "aspect": 0.7568,
    "widths": [
      640,
      1024
    ],
    "fallback": 900,
    "lqip": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAQBQCdASoYACAAPu1qrlAppiQiqAqpMB2JZQC06A1wkA0hN1hob5Cclb7wkldKw7CAAMqPjiNH5b982Z1XnhQXuWIH1FFHExS3hLPTHCsijuiPGvNfbLPjvvyraAnX7g2oY7XC4py7yizSNi8J+dk867oJMkuWXibatDAB6iAdcBAA",
    "role": "Proof - showroom. Ivory and gold suite under a chandelier."
  },
  "showcase": {
    "slug": "showcase",
    "width": 1024,
    "height": 1024,
    "aspect": 1,
    "widths": [
      640,
      1024
    ],
    "fallback": 900,
    "lqip": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAADQBACdASoYABgAPu1urlKppiQiqAgBMB2JQBOmbkgcNx4ef+eEPUC8R8iavO5sAAD9GIijHl5ckxiuvbpgBgZM6dX7VLARzf5wH7eICB1KF1RzzclcCw+B5vXynx5ZoybQdFBHeEQcyHThvnon9OFQNtb+BJGAAAA=",
    "role": "Detail - glazed display cabinet."
  },
  "sofa-blue": {
    "slug": "sofa-blue",
    "width": 1024,
    "height": 1024,
    "aspect": 1,
    "widths": [
      640,
      1024
    ],
    "fallback": 900,
    "lqip": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAAAwBQCdASoYABgAPu1oqU+ppiOiKA1RMB2JZgCdOUFSYASiE+NANP4r6sk/4q2d1+wiAAD+FwHHQdJ48+TIG8mcKn/pDvPj2rspv/uxdUNn+7LyP7iFe/DzNwwaa+5qdy5q7IIcG8HagSr/35Qq77FC8C+4G9B92+FN1E29SF0Q0gE0AAA=",
    "role": "Secondary living - blue and gold embroidered sofa."
  },
  "cabinet-black": {
    "slug": "cabinet-black",
    "width": 1024,
    "height": 1024,
    "aspect": 1,
    "widths": [
      640,
      1024
    ],
    "fallback": 900,
    "lqip": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAwBQCdASoYABgAPuFUpU2opCOiN/qoARAcCWYAnTKEf/gYOfToKUU8H+A+OexonOpMkADOM/YDk+Uw/NUSoWt0G2ucoPgKX1aBnyTvgzGVP20Hf8ieVQxXjyOnjRwOJt6XF+Kl/Nx7v8EapmHDlwBmnDVpa5UxNLzfEncM3doyraTseVUAAA==",
    "role": "Bespoke secondary - black cabinet, brass handles."
  },
  "office": {
    "slug": "office",
    "width": 2048,
    "height": 2048,
    "aspect": 1,
    "widths": [
      640,
      1024
    ],
    "fallback": 900,
    "lqip": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADQBACdASoYABgAPu1kqk6ppaOiKA1RMB2JYgC7AA9nhNItbN/UsCxFcLPMBtchAAD+Ai+edExvZyuS5IJ5gDvyGmwwmAl8wLHh9noyzXUqs4RR2JsKAnGPY5mgCv5/kwhU1tqIpK+vo5eyfdsnbuIQpgAAAA==",
    "role": "Collections - Office & Study. Warm-graded from S=3% to S=22%."
  },
  "office-desk": {
    "slug": "office-desk",
    "width": 2048,
    "height": 2048,
    "aspect": 1,
    "widths": [
      640
    ],
    "fallback": 640,
    "lqip": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADwBACdASoYABgAPu1qrlCppaQiqAqpMB2JYwC7AA3thb61PyE3j6/J9SpBXNq0KAAA/rGD/sQySDe6eP8xmmHGE0k6LXhshUtPsD4TwPe31zbPhKI30/hyyNVZX892BLf88iK+tL05l7KpXuuwAAAA",
    "role": "Interiors - executive desk."
  },
  "office-boardroom": {
    "slug": "office-boardroom",
    "width": 2048,
    "height": 2048,
    "aspect": 1,
    "widths": [
      640
    ],
    "fallback": 640,
    "lqip": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAwBQCdASoYABgAPu1kqU2ppaQiMAgBMB2JZAC06CIOkEaTHE9Ctcr07bzjOl8z/wZMAAD97kU69CD5LLCVIry7U0l08NFbXim4uG07bHh7Rqwx3Lmu4dM7hW4H08S9EZ6R3bEZW9ir3i7P3PaiHfaIbSFU6Bm7BDRfkAAA",
    "role": "Interiors - boardroom table."
  },
  "office-meeting": {
    "slug": "office-meeting",
    "width": 2048,
    "height": 2048,
    "aspect": 1,
    "widths": [
      640
    ],
    "fallback": 640,
    "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADwBACdASoYABgAPu1srlIppaQiqAgBMB2JYwC293+A6OIeP6QJ0QAMtDuRwL3cf4AA/pe9dk8VkkOg1R+BHQTqYoTnKeBfNMQ1ASYUY00u0mZxQWRKiK7rqK9v64WPbTu6HcHQcQgMCAAA",
    "role": "Interiors - meeting table."
  },
  "office-workstation": {
    "slug": "office-workstation",
    "width": 2048,
    "height": 2048,
    "aspect": 1,
    "widths": [
      640
    ],
    "fallback": 640,
    "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAABwBQCdASoYABgAPu1ip06ppSMiMBgMATAdiWIAnTOAga1+rghsffYmajuW1C/BsBH1wibAAP6xf4dtPLgiJgAnPL+q8/qVoSGLBprr6A1X7rnM7kae8K+DQZyTTi6k1zc/6dWWXnlO6aZhN30fSNw8YHpIIAAA",
    "role": "Interiors - workstations."
  },
  "bed-close": {
    "slug": "bed-close",
    "width": 1122,
    "height": 1402,
    "aspect": 0.8003,
    "widths": [
      640,
      1024
    ],
    "fallback": 900,
    "lqip": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAAAQBQCdASoYAB4APu1orE8ppiQiKA1RMB2JQBWHKAAFYQwo95BoonVjFKoaDdmMgD4AAP6DSQREAl50f2J+0AX3G3g9PIitr44atQ9+PUVbP/TNGmRJ3ok6t4T8rxfeMRUVii5htPgg/9oulx1qZxE4ssjfsVmcgJ48eV/tf31oQxFX6RONtDfqg91BqmaneWkImeI3DCsY2Q1VZdYK4OCuHwAAAA==",
    "role": "Proof gallery - closer frame of the emerald bed."
  },
  "living-classic": {
    "slug": "living-classic",
    "width": 1448,
    "height": 1086,
    "aspect": 1.3333,
    "widths": [
      640,
      1024
    ],
    "fallback": 900,
    "lqip": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAABQBACdASoYABIAPulcqE2pJKOiN/VYASAdCWMAtOgL17wwt/Plp8Na/TIAAPrb8k0xHAq6GylTlW9YhdUunAYhihjYYTBOsGW2xUQxZZIth6aeGVg96jV2zPq2uCmExg9+bQ0LCb2LDuWFr8Ou+C+5bOgQAA==",
    "role": "Proof gallery - carved dark-wood suite on marble."
  },
  "material-goldleaf": {
    "slug": "material-goldleaf",
    "width": 1122,
    "height": 1122,
    "aspect": 1,
    "widths": [
      640,
      1024
    ],
    "fallback": 900,
    "lqip": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAQBQCdASoYABgAPu1gq1AppSOisBgIATAdiUAWHYGTjaWPmSd4W4jUJUK7gWDTMsTAAPYejyo6JyijJ+VAVnpjI7KApvWlqcPFTtYyplOJMKmST467cKIEOtVWGuImyKbRTYuXFT0TBfMHa/IGaa+5yiOK8tLGpuXYPWv9nEDNlW5grDuAAA==",
    "role": "Material macro. Carved gilt ornament on a mahogany bed frame."
  },
  "craft-process-poster": {
    "slug": "craft-process-poster",
    "width": 540,
    "height": 960,
    "aspect": 0.5625,
    "widths": [
      480
    ],
    "fallback": 480,
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAwBgCdASoYACsAPt1cpU2opSOiMA1REBuJQBYj8BBU/pK2X7vePDt4SskhYBata9E80uBXO0L4zwgAAP6RTxGCh3ANtkMmH4zvmokP5pw9wSJgsC6S0zG+l99DfQBRE+b/2ZJ+xmi0g4UNf50feiO8XfALmEx9+j28Rsus3cc+KiAlPy1IlICcb952BLNV3T0oAA==",
    "role": "Poster for craft-process"
  },
  "room-reveal-poster": {
    "slug": "room-reveal-poster",
    "width": 1100,
    "height": 618,
    "aspect": 1.7799,
    "widths": [
      640,
      768
    ],
    "fallback": 768,
    "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAABwAwCdASoYAA0APu1iqk2ppaQiMAgBMB2JZQCdABjcuEP8MAAA/rf5F2LrSKJcmFIV+tz05wjn80QgHpa81M7IpDd/VcMPbF2AAA==",
    "role": "Poster for room-reveal"
  },
  "craft-detail-poster": {
    "slug": "craft-detail-poster",
    "width": 900,
    "height": 720,
    "aspect": 1.25,
    "widths": [
      480
    ],
    "fallback": 480,
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAQBQCdASoYABMAPtVao02oJaMiN+gBABqJQBOgBlb+dIwxYNVfn2BZrSOT7W+qx8KAAP7k/SQ7bKUXJy+XQh9EErLSa9pH50kOm3LtSgOw4pLJM9RCbvsFB5AxWhqLzxSq81ZOBjAAAA==",
    "role": "Poster for craft-detail"
  },
  "showroom-tour-poster": {
    "slug": "showroom-tour-poster",
    "width": 1000,
    "height": 424,
    "aspect": 2.3585,
    "widths": [
      640,
      768
    ],
    "fallback": 768,
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQBACdASoYAAoAPu1oqk6ppiQiMAgBMB2JYwCdABwxwdOua1nRh/8t/92QAPryGWTD8OxZ2V8omUEAPbibgwtsAadw09ZJmSm44qQJBePEwswXC2rSD1LjecKUAA==",
    "role": "Poster for showroom-tour"
  },
  "interiors-joinery-poster": {
    "slug": "interiors-joinery-poster",
    "width": 540,
    "height": 960,
    "aspect": 0.5625,
    "widths": [
      480
    ],
    "fallback": 480,
    "lqip": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAACQBgCdASoYACsAPu1iqk6ppSOiKrgN+TAdiUAVgAFBZQp0jULgTlz+N9/PK774WONLmRn0y0ooyaHl7jYAAPyBszmRPNfBOKdIBWIaGBlbF6qQVSOaLqxSRueDE7T18h4kQIRRNpS6NsEmC2swD9VlyBA50iNtI+6qO9pn34C0aTyMdp4K5Ok3to/G/z/9ujwolgxJ2oJLzlo4IuVr5XqRQhOaCMC+MMAAAA==",
    "role": "Poster for interiors-joinery"
  }
};

export const videos = {
  "craft-process": {
    "slug": "craft-process",
    "poster": "craft-process-poster",
    "width": 540,
    "height": 960,
    "aspect": 0.5625,
    "duration": 7,
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAwBgCdASoYACsAPt1cpU2opSOiMA1REBuJQBYj8BBU/pK2X7vePDt4SskhYBata9E80uBXO0L4zwgAAP6RTxGCh3ANtkMmH4zvmokP5pw9wSJgsC6S0zG+l99DfQBRE+b/2ZJ+xmi0g4UNf50feiO8XfALmEx9+j28Rsus3cc+KiAlPy1IlICcb952BLNV3T0oAA==",
    "role": "Bespoke Highlight, 9:16 panel. Real workshop footage."
  },
  "room-reveal": {
    "slug": "room-reveal",
    "poster": "room-reveal-poster",
    "width": 1100,
    "height": 618,
    "aspect": 1.7799,
    "duration": 5.3,
    "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAABwAwCdASoYAA0APu1iqk2ppaQiMAgBMB2JZQCdABjcuEP8MAAA/rf5F2LrSKJcmFIV+tz05wjn80QgHpa81M7IpDd/VcMPbF2AAA==",
    "role": "Intro. An empty room furnishing itself."
  },
  "craft-detail": {
    "slug": "craft-detail",
    "poster": "craft-detail-poster",
    "width": 900,
    "height": 720,
    "aspect": 1.25,
    "duration": 2.4,
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAQBQCdASoYABMAPtVao02oJaMiN+gBABqJQBOgBlb+dIwxYNVfn2BZrSOT7W+qx8KAAP7k/SQ7bKUXJy+XQh9EErLSa9pH50kOm3LtSgOw4pLJM9RCbvsFB5AxWhqLzxSq81ZOBjAAAA==",
    "role": "Material. Macro of embroidery, gilt carving and nailhead trim."
  },
  "showroom-tour": {
    "slug": "showroom-tour",
    "poster": "showroom-tour-poster",
    "width": 1000,
    "height": 424,
    "aspect": 2.3585,
    "duration": 6.5,
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQBACdASoYAAoAPu1oqk6ppiQiMAgBMB2JYwCdABwxwdOua1nRh/8t/92QAPryGWTD8OxZ2V8omUEAPbibgwtsAadw09ZJmSm44qQJBePEwswXC2rSD1LjecKUAA==",
    "role": "Proof. The actual showroom floor, Agrabad Access Road, Chattogram."
  },
  "interiors-joinery": {
    "slug": "interiors-joinery",
    "poster": "interiors-joinery-poster",
    "width": 540,
    "height": 960,
    "aspect": 0.5625,
    "duration": 4.5,
    "lqip": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAACQBgCdASoYACsAPu1iqk6ppSOiKrgN+TAdiUAVgAFBZQp0jULgTlz+N9/PK774WONLmRn0y0ooyaHl7jYAAPyBszmRPNfBOKdIBWIaGBlbF6qQVSOaLqxSRueDE7T18h4kQIRRNpS6NsEmC2swD9VlyBA50iNtI+6qO9pn34C0aTyMdp4K5Ok3to/G/z/9ujwolgxJ2oJLzlo4IuVr5XqRQhOaCMC+MMAAAA==",
    "role": "Interiors. Fitted joinery - shelving, cabinetry, built-ins."
  }
};
