// GENERATED by scripts/process-assets.mjs - do not edit by hand.
// Every entry carries intrinsic width/height so <Picture> can reserve the
// box before load and hold CLS at zero.

export const images = {
  "hero-bed": {
    "slug": "hero-bed",
    "width": 1696,
    "height": 2528,
    "aspect": 0.6709,
    "widths": [
      640,
      1024
    ],
    "fallback": 900,
    "lqip": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAADwBACdASoYACQAPuVeqU2pJSQiMAqpIByJQBZZgEc1L+eioGmAu4SgeKxdJ4glCgAA+aOVnIYc2j3MyW5v7lAavrshypEGx2y6qto6TwjKJ1mDVYU62/SKuy1fjHrr078AOdtrFqalqY5AtsumuUuFFsDFidfFUpkFefYf9nGmEGRhzaP3fJMV+d3LFw6AAAA=",
    "role": "Showroom Wall lead frame. Emerald tufted bed, 1696x2528."
  },
  "showroom-wide": {
    "slug": "showroom-wide",
    "width": 3168,
    "height": 1344,
    "aspect": 2.3571,
    "widths": [
      640,
      1024,
      1600
    ],
    "fallback": 900,
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAwCdASoYAAoAPu1kqk4ppaQiMAgBMB2JQBOgAsNRH7ZW/2z8AAD+mC0cXe6SmKKUJ4ikvINoaL5b+N0XsrrAx3rGg8rSiCF48ArC2VZMBAAA",
    "role": "Intro full-bleed band. Widest frame in the set (3168x1344)."
  },
  "living": {
    "slug": "living",
    "width": 1024,
    "height": 1024,
    "aspect": 1,
    "widths": [
      640,
      1024
    ],
    "fallback": 900,
    "lqip": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADwBACdASoYABgAPu1ur1IppiQiqAgBMB2JZACdMxyBSA6XNjXr8LJYsuBwBB+QOQAA/h3CjTDqyy4bxKXFmqlypvU4Lx5HBT/Xg1O1PCXRftbB7WrrpeuvU502gVfR3El23snfrysYB0No0tKJ8OpINf9Nw6I2rvNTQAAA",
    "role": "Collections - Living. Gilt frame, grey velvet, embroidery."
  },
  "bedroom": {
    "slug": "bedroom",
    "width": 1122,
    "height": 1402,
    "aspect": 0.8003,
    "widths": [
      640,
      1024
    ],
    "fallback": 900,
    "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAACwBQCdASoYAB4APu1cqk4ppKOiMBgMATAdiUATpfregAAv8X/ofp25omPUpJU2Dnkpgqo7ZRQA/H35ZP/dLtmplo86bro6AN/arnxWY3Koftlw8dWLJiGrCRjdxjldLk9Gll/DSJvNSEL7BP/AoXE2d7dvwYGuWVbExEuQ3saLn8ddQ14ScRRTcqCqAAAA",
    "role": "Collections - Bedroom. The only image carrying the brand teal."
  },
  "dining": {
    "slug": "dining",
    "width": 1087,
    "height": 1447,
    "aspect": 0.7512,
    "widths": [
      640,
      1024,
      1087
    ],
    "fallback": 900,
    "lqip": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAABQBQCdASoYACAAPu1qr1CppaQiqAqpMB2JQBdmcBAXlSmXbaCEnmFwFS++jVZyZcZGY8AA6xezA0HQuHWM2YcewsZu92F82QYKxlV8ILY14Egwifi+OTTqMnoUz5pz+klsCnvZbztaX5cbkk2Bs2X+pb/VU3HG+zqT4k1vphMUxs52+ANoO0AAAAA=",
    "role": "Hero panel. Most credible photograph in the set."
  },
  "bespoke": {
    "slug": "bespoke",
    "width": 2048,
    "height": 2048,
    "aspect": 1,
    "widths": [
      640,
      1024
    ],
    "fallback": 900,
    "lqip": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAwBQCdASoYABgAPu1iqE2ppaOiMBgMATAdiWUArAANuW0tY94QKCpZbAX8XaCBAc2EAAD5xw9DkJxTrBb4kSe86md5PgaCj2DF7xtTFs+WyGM/6W172Y9cVVSgv+ZnvdsDi6/TL8s1yJMcjpEAAA==",
    "role": "Collections - Bespoke. Carved chairs on a seamless backdrop."
  },
  "showroom-hall": {
    "slug": "showroom-hall",
    "width": 1344,
    "height": 1776,
    "aspect": 0.7568,
    "widths": [
      640,
      1024
    ],
    "fallback": 900,
    "lqip": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAQBQCdASoYACAAPu1qrlAppiQiqAqpMB2JZQC06A1wkA0hN1hob5Cclb7wkldKw7CAAMqPjiNH5b982Z1XnhQXuWIH1FFHExS3hLPTHCsijuiPGvNfbLPjvvyraAnX7g2oY7XC4py7yizSNi8J+dk867oJMkuWXibatDAB6iAdcBAA",
    "role": "Proof - showroom. Ivory and gold suite under a chandelier."
  },
  "founder": {
    "slug": "founder",
    "width": 816,
    "height": 1020,
    "aspect": 0.8,
    "widths": [
      640
    ],
    "fallback": 640,
    "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAACwBQCdASoYAB4APu1urlIppiQiqAgBMB2JYwCw7BF25eoN1MSd37t/P3Uccj3Y/ZqUp8vQdAAA/ucjR/qEvNKVmbJpufUEkdHfpga1U14SPQkO/xxNEXpA+L1IkbYRqXudEPce3CLxpOOu1bkZCjuJ8slrdQ+NrFLtIDWVqWBwm/xkmUF29v0e5CirgTLAoEX1bmQAAAA=",
    "role": "Proof - MD portrait beside the founder quote."
  },
  "showcase": {
    "slug": "showcase",
    "width": 1024,
    "height": 1024,
    "aspect": 1,
    "widths": [
      640,
      1024
    ],
    "fallback": 900,
    "lqip": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAADQBACdASoYABgAPu1urlKppiQiqAgBMB2JQBOmbkgcNx4ef+eEPUC8R8iavO5sAAD9GIijHl5ckxiuvbpgBgZM6dX7VLARzf5wH7eICB1KF1RzzclcCw+B5vXynx5ZoybQdFBHeEQcyHThvnon9OFQNtb+BJGAAAA=",
    "role": "Detail - glazed display cabinet."
  },
  "sofa-blue": {
    "slug": "sofa-blue",
    "width": 1024,
    "height": 1024,
    "aspect": 1,
    "widths": [
      640,
      1024
    ],
    "fallback": 900,
    "lqip": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAAAwBQCdASoYABgAPu1oqU+ppiOiKA1RMB2JZgCdOUFSYASiE+NANP4r6sk/4q2d1+wiAAD+FwHHQdJ48+TIG8mcKn/pDvPj2rspv/uxdUNn+7LyP7iFe/DzNwwaa+5qdy5q7IIcG8HagSr/35Qq77FC8C+4G9B92+FN1E29SF0Q0gE0AAA=",
    "role": "Secondary living - blue and gold embroidered sofa."
  },
  "cabinet-black": {
    "slug": "cabinet-black",
    "width": 1024,
    "height": 1024,
    "aspect": 1,
    "widths": [
      640,
      1024
    ],
    "fallback": 900,
    "lqip": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAwBQCdASoYABgAPuFUpU2opCOiN/qoARAcCWYAnTKEf/gYOfToKUU8H+A+OexonOpMkADOM/YDk+Uw/NUSoWt0G2ucoPgKX1aBnyTvgzGVP20Hf8ieVQxXjyOnjRwOJt6XF+Kl/Nx7v8EapmHDlwBmnDVpa5UxNLzfEncM3doyraTseVUAAA==",
    "role": "Bespoke secondary - black cabinet, brass handles."
  },
  "bed-close": {
    "slug": "bed-close",
    "width": 1122,
    "height": 1402,
    "aspect": 0.8003,
    "widths": [
      640,
      1024
    ],
    "fallback": 900,
    "lqip": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAAAQBQCdASoYAB4APu1orE8ppiQiKA1RMB2JQBWHKAAFYQwo95BoonVjFKoaDdmMgD4AAP6DSQREAl50f2J+0AX3G3g9PIitr44atQ9+PUVbP/TNGmRJ3ok6t4T8rxfeMRUVii5htPgg/9oulx1qZxE4ssjfsVmcgJ48eV/tf31oQxFX6RONtDfqg91BqmaneWkImeI3DCsY2Q1VZdYK4OCuHwAAAA==",
    "role": "Proof gallery - closer frame of the emerald bed."
  },
  "living-classic": {
    "slug": "living-classic",
    "width": 1448,
    "height": 1086,
    "aspect": 1.3333,
    "widths": [
      640,
      1024
    ],
    "fallback": 900,
    "lqip": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAABQBACdASoYABIAPulcqE2pJKOiN/VYASAdCWMAtOgL17wwt/Plp8Na/TIAAPrb8k0xHAq6GylTlW9YhdUunAYhihjYYTBOsGW2xUQxZZIth6aeGVg96jV2zPq2uCmExg9+bQ0LCb2LDuWFr8Ou+C+5bOgQAA==",
    "role": "Proof gallery - carved dark-wood suite on marble."
  },
  "material-goldleaf": {
    "slug": "material-goldleaf",
    "width": 1122,
    "height": 1122,
    "aspect": 1,
    "widths": [
      640,
      1024
    ],
    "fallback": 900,
    "lqip": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAQBQCdASoYABgAPu1gq1AppSOisBgIATAdiUAWHYGTjaWPmSd4W4jUJUK7gWDTMsTAAPYejyo6JyijJ+VAVnpjI7KApvWlqcPFTtYyplOJMKmST467cKIEOtVWGuImyKbRTYuXFT0TBfMHa/IGaa+5yiOK8tLGpuXYPWv9nEDNlW5grDuAAA==",
    "role": "Showroom Wall. Carved gilt ornament on a mahogany bed frame."
  },
  "gold-leaf-poster": {
    "slug": "gold-leaf-poster",
    "width": 720,
    "height": 900,
    "aspect": 0.8,
    "widths": [
      640,
      720
    ],
    "fallback": 720,
    "lqip": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAACwBACdASoYAB4APu1krE4ppaSiKA1RMB2JQBWF+pALUWbO5cWMk6gx47GkRWWoAP5KfvnwxeK4q1pDB+9Xulnzz6qoZ/bU8pbZ4W3yhHj667GkOrwMSjjs9mVbea5CaLEaIKfsTkpKv99/u9G4UKizZsk9lsADrFe7DmhVmQRAAA==",
    "role": "Poster for gold-leaf"
  },
  "craft-process-poster": {
    "slug": "craft-process-poster",
    "width": 540,
    "height": 960,
    "aspect": 0.5625,
    "widths": [
      480
    ],
    "fallback": 480,
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAwBgCdASoYACsAPt1cpU2opSOiMA1REBuJQBYj8BBU/pK2X7vePDt4SskhYBata9E80uBXO0L4zwgAAP6RTxGCh3ANtkMmH4zvmokP5pw9wSJgsC6S0zG+l99DfQBRE+b/2ZJ+xmi0g4UNf50feiO8XfALmEx9+j28Rsus3cc+KiAlPy1IlICcb952BLNV3T0oAA==",
    "role": "Poster for craft-process"
  },
  "cnc-cut-poster": {
    "slug": "cnc-cut-poster",
    "width": 540,
    "height": 960,
    "aspect": 0.5625,
    "widths": [
      480
    ],
    "fallback": 480,
    "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAQBQCdASoYACsAPtFSoU2oJKMiOrzIAQAaCWUAwrwj3hK/cRfUCdcZCk2gFwISjMIAAP7FfwfOaGhxgJaeW4avAY7oNoE1d2qryc3wb2VbSI2RFMhJpRtYRI7Q8ATL14FFw/+jMYpUwkaBNhvFREXAlZySmqDJe4C/gBfZp+orcKtA8SlZvuIF4IAAAA==",
    "role": "Poster for cnc-cut"
  },
  "cnc-score-poster": {
    "slug": "cnc-score-poster",
    "width": 720,
    "height": 720,
    "aspect": 1,
    "widths": [
      480
    ],
    "fallback": 480,
    "lqip": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAACQBQCdASoYABgAPu1eq02ppKQiMBgMATAdiWcAxNgNyd5ltvVkZ361OSL53+dVMEnW8sJNAAD+1RX3Gg4yuLGnTEDKCiWtYpd6NQG21TqwXwOv1Kr6BDDqLhBGkwTUvxpqCqkketzZs8X73TxHTv2q7agj9HtOt4JT5RP+wAA=",
    "role": "Poster for cnc-score"
  }
};

export const videos = {
  "gold-leaf": {
    "slug": "gold-leaf",
    "poster": "gold-leaf-poster",
    "width": 720,
    "height": 900,
    "aspect": 0.8,
    "duration": 7.5,
    "lqip": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAACwBACdASoYAB4APu1krE4ppaSiKA1RMB2JQBWF+pALUWbO5cWMk6gx47GkRWWoAP5KfvnwxeK4q1pDB+9Xulnzz6qoZ/bU8pbZ4W3yhHj667GkOrwMSjjs9mVbea5CaLEaIKfsTkpKv99/u9G4UKizZsk9lsADrFe7DmhVmQRAAA==",
    "role": "Hero panel, 4:5. Gold leaf laid onto carved wood by hand."
  },
  "craft-process": {
    "slug": "craft-process",
    "poster": "craft-process-poster",
    "width": 540,
    "height": 960,
    "aspect": 0.5625,
    "duration": 7,
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAwBgCdASoYACsAPt1cpU2opSOiMA1REBuJQBYj8BBU/pK2X7vePDt4SskhYBata9E80uBXO0L4zwgAAP6RTxGCh3ANtkMmH4zvmokP5pw9wSJgsC6S0zG+l99DfQBRE+b/2ZJ+xmi0g4UNf50feiO8XfALmEx9+j28Rsus3cc+KiAlPy1IlICcb952BLNV3T0oAA==",
    "role": "Bespoke step 03 (Craft), 9:16 panel. Upholstery by hand."
  },
  "cnc-cut": {
    "slug": "cnc-cut",
    "poster": "cnc-cut-poster",
    "width": 540,
    "height": 960,
    "aspect": 0.5625,
    "duration": 7,
    "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAQBQCdASoYACsAPtFSoU2oJKMiOrzIAQAaCWUAwrwj3hK/cRfUCdcZCk2gFwISjMIAAP7FfwfOaGhxgJaeW4avAY7oNoE1d2qryc3wb2VbSI2RFMhJpRtYRI7Q8ATL14FFw/+jMYpUwkaBNhvFREXAlZySmqDJe4C/gBfZp+orcKtA8SlZvuIF4IAAAA==",
    "role": "Bespoke step 02 (Design). CNC router cutting joinery blanks."
  },
  "cnc-score": {
    "slug": "cnc-score",
    "poster": "cnc-score-poster",
    "width": 720,
    "height": 720,
    "aspect": 1,
    "duration": 6,
    "lqip": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAACQBQCdASoYABgAPu1eq02ppKQiMBgMATAdiWcAxNgNyd5ltvVkZ361OSL53+dVMEnW8sJNAAD+1RX3Gg4yuLGnTEDKCiWtYpd6NQG21TqwXwOv1Kr6BDDqLhBGkwTUvxpqCqkketzZs8X73TxHTv2q7agj9HtOt4JT5RP+wAA=",
    "role": "Material macro, 1:1. V-bit chamfering a panel."
  },
  "showroom-tour": {
    "slug": "showroom-tour",
    "poster": "showroom-wide",
    "width": 1280,
    "height": 720,
    "aspect": 1.7777,
    "duration": 30,
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAwCdASoYAAoAPu1kqk4ppaQiMAgBMB2JQBOgAsNRH7ZW/2z8AAD+mC0cXe6SmKKUJ4ikvINoaL5b+N0XsrrAx3rGg8rSiCF48ArC2VZMBAAA",
    "role": "Showroom Tour video."
  }
};
